# version: 
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
         POSTGRES_USER: sammie
         POSTGRES_PASSWORD: ogoigbe1
         POSTGRES_DB: database_new
    networks:
      - samuel
networks:
  samuel: